services:
  churn-api:
    build: .
    ports:
      - "8000:8000"
    container_name: churn-api-container
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: churn_db
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
